
(defmacro with-stopwatch (&rest body)
  (declare (indent 0) (debug t))
  `(let ((stamp1 (current-time))
	 (result (progn ,@body)))
     (let* ((stamp2 (current-time))
	    (t1 (format "%d.%06d" (nth 1 stamp1) (nth 2 stamp1)))
	    (t2 (format "%d.%06d" (nth 1 stamp2) (nth 2 stamp2)))
	    (ts (calc-eval (concat t2 "-" t1))))
       (list (string-to-number ts) result))))
